version: "3.4"

services:
  spa:
    container_name: "spa-prod"
    build:
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ".:/app"
      - "/app/node_modules"

  authserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mainDB;Port=5432;Database=AuthServerDB;User Id=postgres;Password=admin
    ports:
      - "58944:80"

  reserver:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mainDB;Port=5432;Database=ReServerDB;User Id=postgres;Password=admin
    ports:
      - "58945:80"

  maindb:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./MainDB/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  revproxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./RevProxy:/etc/nginx/conf.d"
      - "<path/to/certs:/etc/ssl/private"
      # configuration: https://www.freecodecamp.org/news/docker-nginx-letsencrypt-easy-secure-reverse-proxy-40165ba3aee2/
