version: "3.4"

services:
  spa:
    container_name: "spa"
    build:
      context: ./SPA
      dockerfile: Dockerfile
    networks:
      - "mainNetwork"

  authserver:
    container_name: "authServer"
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    networks:
      - "mainNetwork"
    depends_on:
      - "maindb"

  reserver:
    container_name: "reServer"
    image: ${DOCKER_REGISTRY-}reserver
    build:
      context: .
      dockerfile: ResourceServer/ResourceServer.Api/Dockerfile
    networks:
      - "mainNetwork"
    depends_on:
      - "maindb"

  maindb:
    container_name: "mainDB"
    image: postgres
    build:
      context: .
      dockerfile: MainDB/Dockerfile
    networks:
      - "mainNetwork"

  revproxy:
    container_name: "revProxy"
    image: nginx
    networks:
      - "mainNetwork"
    depends_on:
      - "spa"
      - "reserver"

networks:
  mainNetwork:
    driver: bridge
