version: "3.4"

services:
  spa:
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5000:4200"
    volumes:
      - "./SPA:/app"
      - "/app/node_modules"

  authserver:
    environment:
      # - ENABLE_POLLING=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mainDB;Port=5432;Database=AuthServerDB;User Id=postgres;Password=admin
    ports:
      - "5550:80"
    volumes:
      - "./AuthServer/:/app"

  reserver:
    environment:
      - ENABLE_POLLING=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mainDB;Port=5432;Database=ReServerDB;User Id=postgres;Password=admin
    ports:
      - "5555:80"
    volumes:
      - "./ResourceServer/:/app"

  maindb:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "AuthServerDB"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./MainDB/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  revproxy:
    ports:
      - "80:80"
    volumes:
      - "./RevProxy:/etc/nginx/conf.d"
